
server:
  port: 8060

# 项目自定义配置
#bbs:
#  xqdxc:
#    code:
#      image:
#        length: 6
#        width: 100
#        height: 30

  #图形验证码过滤器匹配路径
  #bbs.xqdxce.image.url = /user,/user/*
  #bbs.xqdxc.loginPage = /demo-signIn.html
  #bbs.xqdxc.loginType = REDIRECT;


  # Loading class `com.mysql.jdbc.Driver'. \
  # This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. \
  # The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bbs?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: root
      password: fengmysql
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000 #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20
  session:
    store-type: none


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: bbs.xqdxc.model

  #oauth2 client 信息配置
bbs:
  xqdxc:
    oauth2:
      clients[0]:
        clientId: mobile
        clientSecret: gearsofwar3
        accessTokenValiditySeconds: 864000


#logging:
#  level:
#    org:
#      springframework: DEBUG